# Generated by Django 5.0.6 on 2026-09-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Right Point Solutions', max_length=120)),
                ('tagline', models.CharField(default='Security technology for the real world.', help_text='Shown in the footer and used as the fallback social description.', max_length=200)),
                ('hero_kicker', models.CharField(default='Security, engineered for reality', max_length=80)),
                ('hero_heading', models.CharField(default='Make your next move with confidence.', max_length=160)),
                ('hero_body', models.TextField(default='Right Point Solutions brings together technology, field experience and strategic thinking to protect what matters - from the front gate to the data centre.')),
                ('phone_e164', models.CharField(default='+254734030388', help_text='Used for tel: links and click-to-chat.', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, default='254734030388', help_text='Digits only, no plus sign.', max_length=20)),
                ('whatsapp_message', models.CharField(default='Hello Right Point Solutions, I would like advice on a security project.', max_length=200)),
                ('email', models.EmailField(default='rightpointsolutionske@gmail.com', max_length=254)),
                ('street_address', models.CharField(default='6th Floor, Sonalux House, Moi Avenue', max_length=200)),
                ('address_note', models.CharField(default='Next to Nairobi Sports House', max_length=200)),
                ('postal_address', models.CharField(default='P.O. Box 17903-00200', max_length=200)),
                ('city', models.CharField(default='Nairobi', max_length=80)),
                ('country', models.CharField(default='Kenya', max_length=80)),
                ('map_url', models.CharField(blank=True, default='https://maps.google.com/?q=Sonalux+House+Moi+Avenue+Nairobi', max_length=300)),
                ('about_intro', models.TextField(blank=True, default='Right Point Solutions is a Nairobi-based security technology company. We design, install and support the systems that keep people, premises and data safe.')),
                ('about_body', models.TextField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
