# Generated by Django 5.0.6 on 2026-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='working_hours',
            field=models.CharField(default='Mon-Sat, 8am-6pm EAT', help_text='Shown in the bar above the main navigation and on the contact page.', max_length=80),
        ),
    ]
