# Generated by Django 5.0.6 on 2026-10-01 08:36

import django.db.models.deletion
import django.utils.timezone
import invoices.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_inventoryitem'),
        ('quotes', '0003_add_line_taxed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('billing_address', models.TextField(blank=True, help_text='Full billing address for the invoice.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], db_index=True, default='draft', max_length=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(default=invoices.models.default_due_date)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fixed KES discount deducted from the subtotal.', max_digits=12, verbose_name='Discount (KES)')),
                ('apply_vat', models.BooleanField(default=True, help_text='Untick for VAT-exempt customers.', verbose_name='Charge VAT')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('16'), max_digits=5, verbose_name='VAT %')),
                ('bank_name', models.CharField(blank=True, default='Equity Bank Kenya', max_length=120)),
                ('account_name', models.CharField(blank=True, default='Right Point Solutions Ltd', max_length=160)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('routing_number', models.CharField(blank=True, max_length=40, verbose_name='Branch/Sort code')),
                ('payment_method', models.CharField(blank=True, default='Bank Transfer', max_length=80)),
                ('notes', models.TextField(blank=True, default='Thank you for your business!')),
                ('terms', models.TextField(default='Payment is due by the date stated above.\nLate payments may attract interest at 2% per month.\nGoods remain the property of Right Point Solutions until paid in full.\nAny disputes must be raised within 7 days of receipt.')),
                ('internal_note', models.TextField(blank=True, help_text='Never printed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, help_text='Quote this invoice is raised from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='quotes.quote')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=240)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Unit price (KES)')),
                ('taxed', models.BooleanField(default=True, help_text='Tick to apply VAT to this line.', verbose_name='VAT')),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
                ('product', models.ForeignKey(blank=True, help_text='Pick a catalogue item, or leave empty for services.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
    ]
