# Generated by Django 5.0.6 on 2026-09-25 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True, help_text='One or two sentences used on listing pages.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('kicker', models.CharField(blank=True, help_text='Small label above the heading.', max_length=80)),
                ('icon', models.CharField(default='shield', help_text='Name of an inline SVG icon from the icon library: camera, lock, fence, server, compass, clipboard.', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions/')),
                ('image_caption', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True, help_text='Lead paragraph on the detail page.')),
                ('deliverables', models.TextField(blank=True, help_text='One bullet per line - what the engagement includes.')),
                ('outcomes', models.TextField(blank=True, help_text='One bullet per line - the results a client can expect.')),
                ('tags', models.CharField(blank=True, help_text='Comma separated chips shown on the home page cards.', max_length=200)),
            ],
            options={
                'verbose_name': 'solution',
                'verbose_name_plural': 'solutions',
                'ordering': ('order', 'title'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Optional short title for the step.', max_length=80)),
                ('description', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='solutions.solution')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
