# Generated by Django 5.0.6 on 2026-09-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True, help_text='One or two sentences used on listing pages.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('client', models.CharField(max_length=120)),
                ('sector', models.CharField(blank=True, help_text='e.g. Banking, Retail, Campus.', max_length=120)),
                ('country', models.CharField(blank=True, default='Kenya', max_length=80)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. Security & data infrastructure.', max_length=80)),
                ('challenge', models.TextField(blank=True)),
                ('approach', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='One bullet per line - what the delivery covered.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='case-studies/')),
                ('public_source', models.URLField(blank=True, help_text='Publicly verifiable reference link.')),
                ('published_on', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'case study',
                'verbose_name_plural': 'case studies',
                'ordering': ('-published_on', 'order', 'client'),
                'abstract': False,
            },
        ),
    ]
