# Generated by Django 5.0.6 on 2026-10-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Site or installation photo for the card header. If empty, the dark gradient is used.', null=True, upload_to='case-studies/covers/'),
        ),
    ]
