# Generated by Django 5.0.6 on 2026-09-30 10:50

import django.db.models.deletion
import django.utils.timezone
import quotes.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('products', '0003_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('site_location', models.CharField(blank=True, help_text='Where the work or delivery happens.', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='draft', max_length=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(default=quotes.models.default_valid_until)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Applied to the subtotal after line discounts.', max_digits=5, verbose_name='Overall discount %')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('16'), max_digits=5, verbose_name='VAT %')),
                ('notes', models.TextField(blank=True, help_text='Shown to the customer under the lines.')),
                ('terms', models.TextField(default='Prices are in Kenya Shillings and include VAT where shown.\nValid until the date stated above.\nInstallation, configuration and training are included only where listed.\n50% deposit on order, balance on commissioning.')),
                ('internal_note', models.TextField(blank=True, help_text='Never printed.')),
                ('stock_issued', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, help_text='Website enquiry this quote answers, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='contact.contactinquiry')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=240)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Unit price (KES)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Disc. %')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, help_text='Pick a catalogue item, or leave empty for labour and services.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
    ]
