# Generated by Django 5.0.6 on 2026-09-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='apply_vat',
            field=models.BooleanField(default=True, help_text='Untick for VAT-exempt customers or a price quoted exclusive of VAT.', verbose_name='Charge VAT'),
        ),
    ]
