# Generated by Django 5.0.6 on 2026-10-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_apply_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='taxed',
            field=models.BooleanField(default=True, help_text='Tick to apply VAT to this line.', verbose_name='VAT'),
        ),
    ]
