# Generated by Django 5.0.6 on 2026-09-25 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('website', models.URLField(blank=True, help_text='Official manufacturer page for the product family.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True, help_text='One or two sentences used on listing pages.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. Flexible desktop issuance.', max_length=80)),
                ('body', models.TextField(blank=True, help_text='Full description for the detail page.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('features', models.TextField(blank=True, help_text='One specification or capability per line.')),
                ('datasheet_url', models.URLField(blank=True, help_text='Link to the current official datasheet.')),
                ('request_configuration_url', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products appear in the home page selector.')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('solutions', models.ManyToManyField(blank=True, help_text='Capabilities this product supports - used for cross-linking.', related_name='related_products', to='solutions.solution')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ('order', 'title'),
                'abstract': False,
                'indexes': [models.Index(fields=['is_published', 'order'], name='products_pr_is_publ_62aef4_idx')],
            },
        ),
    ]
