# Generated by Django 5.0.6 on 2026-09-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text="Manufacturer's own artwork. Leave empty to show a lettered monogram.", null=True, upload_to='brands/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='speciality',
            field=models.CharField(blank=True, help_text='Short label under the logo, e.g. “Biometric access”.', max_length=80),
        ),
    ]
