# Generated by Django 5.0.6 on 2026-09-30 10:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_logo_brand_speciality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, help_text='Flag the item as low once stock falls to this level.'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_location',
            field=models.CharField(blank=True, help_text='Store, shelf or bin.', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_on_hand',
            field=models.IntegerField(default=0, editable=False, help_text='Maintained by stock movements - never typed in.'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='What we pay per unit.', max_digits=12, verbose_name='Unit cost (KES)'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Default price the quote builder fills in.', max_digits=12, verbose_name='Selling price (KES)'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receive', 'Received (in)'), ('return', 'Returned (in)'), ('issue', 'Issued (out)'), ('adjust', 'Adjustment (+/-)')], default='receive', max_length=10)),
                ('quantity', models.IntegerField(help_text='Units. Give a positive number for received, returned and issued; an adjustment may be negative.')),
                ('reference', models.CharField(blank=True, help_text='Supplier invoice, delivery note or quote number.', max_length=80)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
