# Generated by Django 5.0.6 on 2026-09-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
